import { useEffect, useState } from "react";
import { CalendarDays, CarFront, CheckCircle2, CreditCard, Download, FileText, LogOut, ShieldCheck, Wrench, XCircle } from "lucide-react";
import api, { errorMessage } from "../api.js";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const portalConfig = (token) => ({ headers: { Authorization: `Bearer ${token}` }, skipAdminAuth: true });

export default function CustomerPortal() {
  const [token, setToken] = useState(() => sessionStorage.getItem("yeros_portal_token"));
  const [form, setForm] = useState({ phone: "", code: "" });
  const [account, setAccount] = useState(null);
  const [signature, setSignature] = useState("");
  const [error, setError] = useState("");
  const [booking, setBooking] = useState({ vehicle: "", serviceType: "General service", scheduledAt: "", location: "", notes: "" });

  async function load(currentToken = token) {
    if (!currentToken) return;
    try { setAccount((await api.get("/portal/account", portalConfig(currentToken))).data); }
    catch (requestError) { setError(errorMessage(requestError)); sessionStorage.removeItem("yeros_portal_token"); setToken(null); }
  }
  useEffect(() => { load(); }, [token]);
  async function login(event) { event.preventDefault(); try { const { data } = await api.post("/portal/login", form); sessionStorage.setItem("yeros_portal_token", data.token); setToken(data.token); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function decide(id, decision) { if (!signature.trim()) return setError("Enter your full name before approving or declining."); try { await api.post(`/portal/estimates/${id}/decision`, { decision, signature }, portalConfig(token)); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function requestAppointment(event) { event.preventDefault(); try { await api.post("/portal/appointments", booking, portalConfig(token)); setBooking({ vehicle: "", serviceType: "General service", scheduledAt: "", location: "", notes: "" }); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function invoice(order) { try { const response = await api.get(`/portal/orders/${order._id}/invoice`, { ...portalConfig(token), responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `Invoice-${order.orderNumber}.pdf`; link.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function pay(order) { try { const { data } = await api.post(`/portal/orders/${order._id}/payment-link`, {}, portalConfig(token)); window.location.assign(data.url); } catch (requestError) { setError(errorMessage(requestError)); } }

  if (!token) return <div className="portal-login"><main><img src="/yeros-auto-logo.png" alt="Yeros Auto Services" /><span>Customer portal</span><h1>Your vehicle service, in one place.</h1><p>View appointments, estimates, repairs and payments.</p>{error && <div className="form-error">{error}</div>}<form onSubmit={login}><label>Phone number<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} required /></label><label>6-digit access code<input inputMode="numeric" maxLength="6" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} required /></label><button><ShieldCheck />Secure sign in</button></form><small>Request an access code from Yeros Auto Services.</small></main></div>;
  if (!account) return <div className="portal-login"><main><p>{error || "Loading your account..."}</p></main></div>;
  return <div className="customer-portal"><header><img src="/yeros-auto-logo.png" alt="Yeros Auto Services" /><div><span>Customer portal</span><strong>{account.customer.name}</strong></div><button onClick={() => { sessionStorage.removeItem("yeros_portal_token"); setToken(null); }}><LogOut />Sign out</button></header><main>{error && <div className="form-error">{error}</div>}<section className="portal-welcome"><span>Welcome back</span><h1>Your garage</h1><p>Everything Yeros Auto Services has on file for your vehicles.</p></section>
    <section className="portal-vehicles">{account.vehicles.map((vehicle) => <article key={vehicle._id}><CarFront /><div><h2>{vehicle.year} {vehicle.make} {vehicle.model}</h2><p>{vehicle.plate || "No plate"} · {Number(vehicle.mileage || 0).toLocaleString()} miles</p></div><span>Next oil service<strong>{vehicle.oilChange?.lastMileage ? `${Number(vehicle.oilChange.lastMileage + vehicle.oilChange.intervalMiles).toLocaleString()} mi` : "Not scheduled"}</strong></span></article>)}</section>
    <section className="portal-grid"><article><header><CalendarDays /><h2>Appointments</h2></header>{account.appointments.slice(0, 5).map((item) => <div key={item._id}><strong>{item.title}</strong><span>{new Date(item.scheduledAt).toLocaleString()} · {item.status}</span></div>)}</article><article><header><Wrench /><h2>Repair status</h2></header>{account.orders.slice(0, 5).map((item) => <div className="portal-order" key={item._id}><strong>{item.orderNumber}</strong><span>{item.services.map((service) => service.description).join(", ")} · {(item.workflowStage || item.status).replaceAll("_", " ")}</span><nav><button onClick={() => invoice(item)}><Download />Invoice</button>{item.paymentStatus !== "paid" && <button onClick={() => pay(item)}><CreditCard />Pay online</button>}</nav></div>)}</article></section>
    <section className="portal-booking"><header><CalendarDays /><div><h2>Request an appointment</h2><p>Choose the vehicle, service and preferred time. The shop will confirm availability.</p></div></header><form onSubmit={requestAppointment}><label>Vehicle<select required value={booking.vehicle} onChange={(e) => setBooking({ ...booking, vehicle: e.target.value })}><option value="">Choose vehicle</option>{account.vehicles.map((vehicle) => <option value={vehicle._id} key={vehicle._id}>{vehicle.year} {vehicle.make} {vehicle.model}</option>)}</select></label><label>Service<input required value={booking.serviceType} onChange={(e) => setBooking({ ...booking, serviceType: e.target.value })} /></label><label>Preferred date and time<input type="datetime-local" required value={booking.scheduledAt} onChange={(e) => setBooking({ ...booking, scheduledAt: e.target.value })} /></label><label>Service address<input value={booking.location} onChange={(e) => setBooking({ ...booking, location: e.target.value })} /></label><label className="span-2">Notes<textarea value={booking.notes} onChange={(e) => setBooking({ ...booking, notes: e.target.value })} /></label><button>Send request</button></form></section>
    <section className="portal-estimates"><header><FileText /><div><h2>Estimates</h2><p>Review and approve recommendations electronically.</p></div></header>{account.estimates.map((estimate) => <article key={estimate._id}><div><strong>{estimate.estimateNumber}</strong><span>{estimate.vehicle?.year} {estimate.vehicle?.make} {estimate.vehicle?.model}</span></div><b>{money.format(estimate.total)}</b><i>{estimate.status}</i>{["draft", "sent"].includes(estimate.status) && <div className="portal-decision"><input value={signature} onChange={(e) => setSignature(e.target.value)} placeholder="Full name signature" /><button onClick={() => decide(estimate._id, "declined")}><XCircle />Decline</button><button onClick={() => decide(estimate._id, "approved")}><CheckCircle2 />Approve</button></div>}</article>)}</section>
    <section className="portal-grid single"><article><header><CreditCard /><h2>Payments</h2></header>{account.payments.slice(0, 5).map((item) => <div key={item._id}><strong>{money.format(item.amount)}</strong><span>{item.method} · {item.status}</span></div>)}</article></section>
  </main></div>;
}
