import { useEffect, useState } from "react";
import { Banknote, CircleDollarSign, CreditCard, Plus, Receipt, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import api, { errorMessage } from "../api.js";
import Modal from "../components/Modal.jsx";
import { Alert, Empty, Loading } from "../components/PageState.jsx";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const expenseBlank = { category: "fuel", description: "", amount: 0, date: new Date().toISOString().slice(0, 10), vendor: "", paymentMethod: "" };
const paymentBlank = { customer: "", workOrder: "", type: "invoice", amount: 0, method: "cash", status: "paid", reference: "" };

export default function Finance() {
  const [data, setData] = useState(null);
  const [customers, setCustomers] = useState([]);
  const [orders, setOrders] = useState([]);
  const [modal, setModal] = useState("");
  const [expense, setExpense] = useState(expenseBlank);
  const [payment, setPayment] = useState(paymentBlank);
  const [error, setError] = useState("");
  async function load() {
    try {
      const [financeResponse, customerResponse, orderResponse] = await Promise.all([api.get("/finance"), api.get("/customers"), api.get("/work-orders")]);
      setData(financeResponse.data); setCustomers(customerResponse.data); setOrders(orderResponse.data);
    } catch (requestError) { setError(errorMessage(requestError)); }
  }
  useEffect(() => { load(); }, []);
  async function saveExpense(event) { event.preventDefault(); try { await api.post("/finance/expenses", expense); setModal(""); setExpense(expenseBlank); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function savePayment(event) { event.preventDefault(); try { await api.post("/finance/payments", { ...payment, workOrder: payment.workOrder || null }); setModal(""); setPayment(paymentBlank); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  return <div className="page business-module finance-page"><Alert message={error} onClose={() => setError("")} /><header className="module-hero"><div><span className="eyebrow">True business performance</span><h1>Financial control</h1><p>Sales, collections, operating expenses and real net profit in one view.</p></div><div className="finance-actions"><button className="button secondary" onClick={() => setModal("expense")}><Receipt />Add expense</button><button className="button primary" onClick={() => setModal("payment")}><CreditCard />Record payment</button></div></header>
    {!data ? <Loading /> : <><section className="finance-kpis"><article><CircleDollarSign /><span>Sales</span><strong>{money.format(data.summary.sales)}</strong></article><article><Banknote /><span>Collected</span><strong>{money.format(data.summary.collected)}</strong></article><article><TrendingDown /><span>Operating expenses</span><strong>{money.format(data.summary.operatingExpenses)}</strong></article><article className={data.summary.netProfit >= 0 ? "positive" : "negative"}><TrendingUp /><span>Net profit</span><strong>{money.format(data.summary.netProfit)}</strong></article></section>
      <section className="finance-grid"><article className="solid-panel"><header><Receipt /><div><h2>Operating expenses</h2><p>Fuel, tools, payroll, insurance and overhead.</p></div></header>{data.expenses.length ? <div className="finance-list">{data.expenses.map((item) => <div key={item._id}><span className={`expense-category ${item.category}`}>{item.category}</span><div><strong>{item.description}</strong><small>{item.vendor || "No vendor"} · {new Date(item.date).toLocaleDateString()}</small></div><b>{money.format(item.amount)}</b></div>)}</div> : <Empty>No expenses recorded this month.</Empty>}</article>
      <article className="solid-panel"><header><WalletCards /><div><h2>Payment activity</h2><p>Deposits and invoice collections.</p></div></header>{data.payments.length ? <div className="finance-list">{data.payments.map((item) => <div key={item._id}><span className="payment-method">{item.method}</span><div><strong>{item.customer?.name}</strong><small>{item.workOrder?.orderNumber || item.type} · {item.status}</small></div><b>{money.format(item.amount)}</b></div>)}</div> : <Empty>No payments recorded this month.</Empty>}</article></section>
      <section className="solid-panel category-spend"><h2>Expenses by category</h2><div>{Object.entries(data.summary.categories || {}).map(([category, amount]) => <article key={category}><span>{category}</span><strong>{money.format(amount)}</strong><i style={{ width: `${Math.min(100, amount / Math.max(...Object.values(data.summary.categories), 1) * 100)}%` }} /></article>)}</div></section></>}
    {modal === "expense" && <Modal title="Record operating expense" onClose={() => setModal("")}><form className="form-grid" onSubmit={saveExpense}><label>Category<select value={expense.category} onChange={(e) => setExpense({ ...expense, category: e.target.value })}>{["fuel","tools","payroll","insurance","rent","parts","marketing","software","taxes","other"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Description<input value={expense.description} onChange={(e) => setExpense({ ...expense, description: e.target.value })} required /></label><label>Amount<input type="number" min=".01" step=".01" value={expense.amount} onChange={(e) => setExpense({ ...expense, amount: Number(e.target.value) })} required /></label><label>Date<input type="date" value={expense.date} onChange={(e) => setExpense({ ...expense, date: e.target.value })} /></label><label>Vendor<input value={expense.vendor} onChange={(e) => setExpense({ ...expense, vendor: e.target.value })} /></label><label>Payment method<input value={expense.paymentMethod} onChange={(e) => setExpense({ ...expense, paymentMethod: e.target.value })} /></label><div className="form-actions span-2"><button className="button primary">Save expense</button></div></form></Modal>}
    {modal === "payment" && <Modal title="Record customer payment" onClose={() => setModal("")}><form className="form-grid" onSubmit={savePayment}><label>Customer<select value={payment.customer} onChange={(e) => setPayment({ ...payment, customer: e.target.value })} required><option value="">Select customer</option>{customers.map((customer) => <option key={customer._id} value={customer._id}>{customer.name}</option>)}</select></label><label>Work order<select value={payment.workOrder} onChange={(e) => setPayment({ ...payment, workOrder: e.target.value })}><option value="">General payment</option>{orders.filter((order) => !payment.customer || (order.customer?._id || order.customer) === payment.customer).map((order) => <option key={order._id} value={order._id}>{order.orderNumber}</option>)}</select></label><label>Type<select value={payment.type} onChange={(e) => setPayment({ ...payment, type: e.target.value })}><option value="deposit">Deposit</option><option value="invoice">Invoice payment</option><option value="refund">Refund</option></select></label><label>Method<select value={payment.method} onChange={(e) => setPayment({ ...payment, method: e.target.value })}>{["cash","card","zelle","cash_app","check","online","other"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Amount<input type="number" min=".01" step=".01" value={payment.amount} onChange={(e) => setPayment({ ...payment, amount: Number(e.target.value) })} required /></label><label>Reference<input value={payment.reference} onChange={(e) => setPayment({ ...payment, reference: e.target.value })} /></label><div className="form-actions span-2"><button className="button primary">Record payment</button></div></form></Modal>}
  </div>;
}
