import { useEffect, useState } from "react";
import { Gift, MessageCircle, Star, Users } from "lucide-react";
import api, { errorMessage } from "../api.js";
import { Alert, Loading } from "../components/PageState.jsx";
export default function Marketing() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [form, setForm] = useState({ code: "", title: "", discountType: "percent", discountValue: 10, description: "" });
  async function load() { try { setData((await api.get("/marketing")).data); } catch (e) { setError(errorMessage(e)); } }
  useEffect(() => { load(); }, []);
  async function create(e) { e.preventDefault(); try { await api.post("/marketing/offers", form); setForm({ code: "", title: "", discountType: "percent", discountValue: 10, description: "" }); await load(); } catch (err) { setError(errorMessage(err)); } }
  async function review(customer) { try { const { data: link } = await api.post("/marketing/review-link", { customer }); if (link.whatsappUrl) window.open(link.whatsappUrl, "_blank", "noopener"); else setError("This customer does not have a phone number"); } catch (e) { setError(errorMessage(e)); } }
  if (!data) return <Loading />;
  return <div className="page business-module"><Alert message={error} onClose={() => setError("")} /><header className="module-hero"><div><span className="eyebrow">Customer growth</span><h1>Marketing & reputation</h1><p>Bring customers back, request reviews and create trackable offers from one place.</p></div><div className="hero-count"><Star />Growth center</div></header>
    <section className="business-kpis"><article><Users /><span>Total customers</span><strong>{data.summary.customers}</strong></article><article><MessageCircle /><span>Review candidates</span><strong>{data.summary.reviewCandidates}</strong></article><article className={data.summary.dormant ? "attention" : ""}><Users /><span>Reactivation list</span><strong>{data.summary.dormant}</strong></article><article><Gift /><span>Active offers</span><strong>{data.summary.activeOffers}</strong></article></section>
    <section className="marketing-grid"><form className="solid-panel offer-form" onSubmit={create}><header><Gift /><div><h2>Create an offer</h2><p>Coupons for retention, referrals or seasonal service.</p></div></header><label>Code<input required value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} placeholder="OIL10" /></label><label>Title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><div><label>Type<select value={form.discountType} onChange={(e) => setForm({ ...form, discountType: e.target.value })}><option value="percent">Percent</option><option value="fixed">Fixed amount</option></select></label><label>Value<input type="number" min="0" required value={form.discountValue} onChange={(e) => setForm({ ...form, discountValue: Number(e.target.value) })} /></label></div><label>Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><button className="button primary">Publish offer</button>{data.offers.map((offer) => <div className="offer-chip" key={offer._id}><b>{offer.code}</b><span>{offer.title}</span><strong>{offer.discountValue}{offer.discountType === "percent" ? "%" : "$"}</strong></div>)}</form>
      <section className="solid-panel reactivation"><header><Users /><div><h2>Customers to reactivate</h2><p>No recent completed service in the last 90 days.</p></div></header>{data.dormant.map((customer) => <article key={customer._id}><div><strong>{customer.name}</strong><small>{customer.phone || customer.email || "No contact information"}</small></div>{customer.phone && <a href={`https://wa.me/${customer.phone.replace(/\D/g, "")}`} target="_blank" rel="noreferrer"><MessageCircle />WhatsApp</a>}</article>)}</section>
      <section className="solid-panel review-list"><header><Star /><div><h2>Review follow-up</h2><p>Recent completed work ready for a review request.</p></div></header>{data.reviewCandidates.slice(0, 12).map((order) => <article key={order._id}><div><strong>{order.customer?.name}</strong><small>{order.orderNumber}</small></div><button onClick={() => review(order.customer?._id)}><Star />Request review</button></article>)}</section></section>
  </div>;
}
