import { useEffect, useState } from "react";
import { PackageCheck, Plus, ShoppingCart } from "lucide-react";
import api, { errorMessage } from "../api.js";
import Modal from "../components/Modal.jsx";
import { Alert, Empty, Loading } from "../components/PageState.jsx";
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
export default function PurchaseOrders() {
  const [orders, setOrders] = useState(null); const [parts, setParts] = useState([]); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ supplier: "", supplierPhone: "", expectedAt: "", notes: "", part: "", quantity: 1 });
  async function load() { try { const [po, inventory] = await Promise.all([api.get("/purchases"), api.get("/inventory", { params: { limit: 100 } })]); setOrders(po.data); setParts(inventory.data.items); } catch (e) { setError(errorMessage(e)); } }
  useEffect(() => { load(); }, []);
  async function save(e) { e.preventDefault(); try { const part = parts.find((item) => item._id === form.part); await api.post("/purchases", { supplier: form.supplier, supplierPhone: form.supplierPhone, expectedAt: form.expectedAt || undefined, notes: form.notes, status: "ordered", items: [{ part: form.part, quantity: Number(form.quantity), cost: part?.cost || 0 }] }); setOpen(false); await load(); } catch (err) { setError(errorMessage(err)); } }
  async function receive(id) { try { await api.post(`/purchases/${id}/receive`, {}); await load(); } catch (e) { setError(errorMessage(e)); } }
  if (!orders) return <Loading />;
  return <div className="page business-module"><Alert message={error} onClose={() => setError("")} /><header className="module-hero"><div><span className="eyebrow">Supply chain</span><h1>Purchase orders</h1><p>Order parts, track expected deliveries and add received stock automatically.</p></div><button className="button primary" onClick={() => setOpen(true)}><Plus />New purchase order</button></header>
    <section className="solid-table-card suite-table">{orders.length ? <div className="table-scroll"><table><thead><tr><th>PO</th><th>Supplier</th><th>Items</th><th>Expected</th><th>Total</th><th>Status</th><th /></tr></thead><tbody>{orders.map((order) => <tr key={order._id}><td><strong>{order.purchaseOrderNumber}</strong></td><td>{order.supplier}<small>{order.supplierPhone}</small></td><td>{order.items.map((item) => `${item.quantity} × ${item.name}`).join(", ")}</td><td>{order.expectedAt ? new Date(order.expectedAt).toLocaleDateString() : "—"}</td><td>{money.format(order.total || 0)}</td><td><span className={`stock-pill ${order.status === "cancelled" ? "low" : ""}`}>{order.status}</span></td><td>{!["received", "cancelled"].includes(order.status) && <button className="button compact" onClick={() => receive(order._id)}><PackageCheck />Receive</button>}</td></tr>)}</tbody></table></div> : <Empty icon={ShoppingCart} title="No purchase orders yet" description="Create the first supplier order." />}</section>
    {open && <Modal title="New purchase order" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={save}><label>Supplier<input required value={form.supplier} onChange={(e) => setForm({ ...form, supplier: e.target.value })} /></label><label>Supplier phone<input value={form.supplierPhone} onChange={(e) => setForm({ ...form, supplierPhone: e.target.value })} /></label><label>Part<select required value={form.part} onChange={(e) => setForm({ ...form, part: e.target.value })}><option value="">Choose part</option>{parts.map((item) => <option key={item._id} value={item._id}>{item.sku} · {item.name}</option>)}</select></label><label>Quantity<input type="number" min="1" required value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} /></label><label>Expected date<input type="date" value={form.expectedAt} onChange={(e) => setForm({ ...form, expectedAt: e.target.value })} /></label><label className="span-2">Notes<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><div className="form-actions span-2"><button className="button primary">Create order</button></div></form></Modal>}
  </div>;
}
